# ==========================================================================
# CRE WORKFLOW SETTINGS FILE
# ==========================================================================
staging-settings:
    user-workflow:
        workflow-name: "rewall-enclave-grantee-staging"
    workflow-artifacts:
        workflow-path: "./main.ts"
        config-path: "./config.json"
        secrets-path: "../secrets.yaml"

# ==========================================================================
production-settings:
    user-workflow:
        workflow-name: "rewall-enclave-grantee"
    workflow-artifacts:
        workflow-path: "./main.ts"
        config-path: "./config.json"
        secrets-path: "../secrets.yaml"
